name: Common action for Marp team
description: Common action for Marp team
author: Marp team
inputs:
  task:
    description: The name of task
    required: true
  token:
    description: Token string for GitHub
    required: true

  # "release" task
  preRelease:
    description: Mark the release as pre-release

  # "upload" task
  files:
    description: Comma-separated string for upload files or directories
runs:
  using: node16
  main: lib/main.js
